package com.erongdu.wireless.permissions.processor.utils;

/**
 * Author: chenwei
 * E-mail: cw@erongdu.com
 * Date: 2018/1/11 下午8:15
 * <p>
 * Description:
 */
public class Consts {
    //Generate
    public static final  String PROJECT                           = "RDPermission";
    public static final  String SEPARATOR                         = "$$";
    public static final  String PACKAGE_OF_GENERATE_FILE          = "com.erongdu.wireless.permissions";
    public static final  String WARNING_TIPS                      = "DO NOT EDIT THIS FILE!!! IT WAS GENERATE AUTOMATICALLY.";
    //Package name
    public static final  String FACADE_PACKAGE                    = "com.erongdu.wireless.permissions";
    public static final  String ANNOTATION_PACKAGE                = ".annotation";
    public static final  String PERMISSIONSLIB_PACKAGE            = ".permissionslib";
    //AnnotationType
    public static final  String ANNOTATION_TYPE_PERMISSIONDENIED  = FACADE_PACKAGE + ANNOTATION_PACKAGE + ".PermissionDenied";
    public static final  String ANNOTATION_TYPE_PERMISSIONGRANTED = FACADE_PACKAGE + ANNOTATION_PACKAGE + ".PermissionGranted";
    public static final  String ANNOTATION_TYPE_REQUESTCODE       = FACADE_PACKAGE + ANNOTATION_PACKAGE + ".RequestCode";
    public static final  String ANNOTATION_TYPE_PMARRAY           = FACADE_PACKAGE + ANNOTATION_PACKAGE + ".PMArray";
    public static final  String ANNOTATION_TYPE_GRANTREULT        = FACADE_PACKAGE + ANNOTATION_PACKAGE + ".GrantResult";
    //interface
    public static final  String INTERFACE_PERMISSIONCALLBACK      = FACADE_PACKAGE + PERMISSIONSLIB_PACKAGE + ".proxy.PermissionCallBack";
    //Annotation mapping name
    public static final  String ANNOTATION_MAPPING_REQUESTCODE    = "requestCode";
    public static final  String ANNOTATION_MAPPING_PERMISSIONS    = "permissions";
    public static final  String ANNOTATION_MAPPING_GRANTRESULTS   = "grantResults";
    // Log
    public static final  String PREFIX_OF_LOGGER                  = PROJECT + "::Compiler ";
    //Element type
    public static final  String TYPEMIRROR_INT                    = "int";
    public static final  String TYPEMIRROR_ARRAY_INT              = "int[]";
    public static final  String TYPEMIRROR_ARRAY_STRING           = "java.lang.String[]";
    //parameter name
    public static final  String ANNOTATION_NAME_REQUESTCODE       = "requestCode";
    public static final  String ANNOTATION_NAME_PMARRAY           = "pmArray";
    public static final  String ANNOTATION_NAME_GRANTREULT        = "GrantResult";
    //method name
    public static final  String METHOD_PERMISSIONGRANTED          = "permissionGranted";
    public static final  String METHOD_PERMISSIONDENIED           = "permissionDenied";
    public static final  String METHOD_PERMISSIONRATIONALE           = "permissionRationale";
    // Java type
    private static final String LANG                              = "java.lang";
    public static final  String BYTE                              = LANG + ".Byte";
    public static final  String SHORT                             = LANG + ".Short";
    public static final  String INTEGER                           = LANG + ".Integer";
    public static final  String LONG                              = LANG + ".Long";
    public static final  String FLOAT                             = LANG + ".Float";
    public static final  String DOUBEL                            = LANG + ".Double";
    public static final  String BOOLEAN                           = LANG + ".Boolean";
    public static final  String STRING                            = LANG + ".String";
    public static final  String OBJECT                            = LANG + ".Object";
    // Primitive Java type
    public static final  String PRIMITIVE_BYTE                    = "byte";
    public static final  String PRIMITIVE_SHORT                   = "short";
    public static final  String PRIMITIVE_INTEGER                 = "int";
    public static final  String PRIMITIVE_LONG                    = "long";
    public static final  String PRIMITIVE_FLOAT                   = "float";
    public static final  String PRIMITIVE_DOUBEL                  = "double";
    public static final  String PRIMITIVE_BOOLEAN                 = "boolean";
}